version: "3.2"

services:
  xmrig:
    build: ./xmrig
    links:
      - p2pool
    volumes:
      - xmrig:/srv

  p2pool:
    build: ./p2pool
    links:
      - monerod
    volumes:
      - p2pool:/srv

  monerod:
    build: ./monerod
    volumes:
      - blockchain:/srv

volumes:
  blockchain:
  p2pool:
  xmrig:
