version: "3.2"

services:
  p2pool:
    image: gbenson/p2pool
    init: true
    links:
      - monerod
    ports:
      - 0.0.0.0:3333:3333/tcp  # stratum port
      - 0.0.0.0:37888:37888/tcp  # p2pool-mini p2p port
    volumes:
      - p2pool:/srv/p2pool
      - /dev/null:/srv/p2pool/p2pool.log

  monerod:
    image: gbenson/monero-node
    init: true
    ports:
      - 0.0.0.0:18080:18080/tcp  # p2p port
      - 127.0.0.1:18081:18081/tcp  # unrestricted RPC port
    volumes:
      - monerod:/srv/monerod

volumes:
  monerod:
    external: true
  p2pool:
    external: true
