version: "3.2"

services:
  monerod:
    image: gbenson/monero-node
    container_name: monerod
    restart: unless-stopped
    init: true
    ports:
      - 0.0.0.0:18080:18080/tcp  # p2p port
    volumes:
      - monerod:/srv/monerod
      - /dev/null:/srv/monerod/bitmonero.log
    command:
      - --non-interactive
      - --data-dir=/srv/monerod
      - --log-level=0
      - --rpc-bind-ip=0.0.0.0
      - --confirm-external-bind
      - --zmq-pub=tcp://0.0.0.0:18083
      - --no-igd
      - --add-priority-node=p2pmd.xmrvsbeast.com:18080
      - --add-priority-node=nodes.hashvault.pro:18080
      - --disable-dns-checkpoints
      - --enable-dns-blocklist
      - --config-file=/srv/monerod/bitmonero.conf

  p2pool:
    image: gbenson/p2pool
    container_name: p2pool
    restart: unless-stopped
    init: true
    depends_on:
      monerod:
        condition: service_healthy
    links:
      - monerod
    ports:
      - 0.0.0.0:3333:3333/tcp  # stratum port
      - 0.0.0.0:37888:37888/tcp  # p2pool-mini p2p port
    volumes:
      - p2pool:/srv/p2pool
      - /dev/null:/srv/p2pool/p2pool.log
    command:
      - --host
      - monerod
      - --mini
      - --no-upnp
      - --wallet
      - "4APvq9TNgrBSYjZ4AvVJpvgh493nzMjmzUNK6EL4aAJiGr1d\
         SGQXx1o5Kk14F4Gj1zDwdfyuBbSwDFKmmFhovTrX976BRNe"

volumes:
  monerod:
    external: true
  p2pool:
    external: true
