version: "3.2"

services:
  xmrig:
    build: ./xmrig
    init: true
    links:
      - p2pool
    volumes:
      - xmrig:/srv

  p2pool:
    build: ./p2pool
    init: true
    links:
      - monerod
    ports:
      - 3333:3333  # stratum port
      - 37888:37888  # p2pool-mini p2p port
    volumes:
      - p2pool:/srv/p2pool
      - /dev/null:/srv/p2pool/p2pool.log

  monerod:
    image: gbenson/monero-node
    init: true
    ports:
      - 18080:18080
    volumes:
      - monerod:/srv/monerod

volumes:
  monerod:
    external: true
  p2pool:
    external: true
  xmrig:
