version: "3.2"

services:
  p2pool:
    image: gbenson/p2pool
    container_name: p2pool
    restart: unless-stopped
    init: true
    links:
      - monerod
    ports:
      - 0.0.0.0:3333:3333/tcp  # stratum port
      - 0.0.0.0:37888:37888/tcp  # p2pool-mini p2p port
    volumes:
      - p2pool:/srv/p2pool
      - /dev/null:/srv/p2pool/p2pool.log
    command:
      - --host
      - monerod
      - --mini
      - --no-upnp
      - --wallet
      - 4APvq9TNgrBSYjZ4AvVJpvgh493nzMjmzUNK6EL4aAJiGr1dSGQXx1o5Kk14F4Gj1zDwdfyuBbSwDFKmmFhovTrX976BRNe

  monerod:
    image: gbenson/monero-node
    container_name: monerod
    restart: unless-stopped
    init: true
    ports:
      - 0.0.0.0:18080:18080/tcp  # p2p port
    volumes:
      - monerod:/srv/monerod
      - /dev/null:/srv/monerod/bitmonero.log
    command:
      - --data-dir=/srv/monerod
      - --log-level=0
      - --rpc-bind-ip=0.0.0.0
      - --confirm-external-bind
      - --zmq-pub=tcp://0.0.0.0:18083
      - --no-igd
      - --disable-dns-checkpoints
      - --config-file=/srv/monerod/bitmonero.conf

  rpc-proxy:
    image: httpd:2.4-bookworm
    container_name: rpc-proxy
    restart: unless-stopped
    ports:
      - 127.0.0.1:18081:18081/tcp  # unrestricted RPC
    volumes:
      - ./rpc-proxy/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./rpc-proxy/.htpasswd.digest:/usr/local/apache2/conf/htpasswd.digest

volumes:
  monerod:
    external: true
  p2pool:
    external: true
