[project]
name = "rigstatus"
version = "0.0.0"
dependencies = [
    "redis",
]

[project.optional-dependencies]
dev = [
    "flake8",
    "pytest",
]

[project.scripts]
rs = "rs.main:main"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
